version: "3.3"

services:
  nginxplus:
    container_name: nginxplus
    build:
      context: docker/nginxplus
  nodejs:
    container_name: node1
    build: 
      context: docker/nodejs
      args: 
        port : 1337
    volumes: 
      - data-project:/srv/nodeProject/current/
    ports: 
      - 49160:1337
    environment: 
      PORT : 1337
  nodejs2:
    container_name: node2
    build: 
      context: docker/nodejs
      args: 
        port : 3000
    volumes: 
      - data-project:/srv/nodeProject2/current/
    ports: 
      - 49161:3000
    environment: 
      PORT : 3000
  nginx:
    container_name: nginx-loadbalancing
    build: 
      context: docker/nginx
    ports:
      - 80:8084
    depends_on: 
      - nodejs
      - nodejs2
  mysql:
    container_name: mysql-dev
    build: docker/mysql
    volumes: 
      - data-project:/var/lib/mysql
    ports:
      - "3366:3306"
    environment:
      # some variable to replace
      MYSQL_DATABASE: "security_bdd"
      MYSQL_USER: "bill"
      MYSQL_PASSWORD: "12345678"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"

volumes: 
  data-project:
